# Generated by Django 2.1.3 on 2018-12-08 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactslist', '0002_auto_20181116_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=20)),
                ('car_fuel', models.CharField(max_length=20)),
                ('car_Auto', models.CharField(max_length=20)),
                ('car_Image', models.CharField(max_length=255)),
                ('car_Country', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=20)),
                ('Country', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('e_mail', models.EmailField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UsersPick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactslist.Carinfo')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactslist.User')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='carinfo',
            name='car_Cate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactslist.Category'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='car_Company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactslist.Company'),
        ),
    ]
